import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useState } from "react";
import { ActivityIndicator, Image, Pressable, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { fetchPublicAgency, type PublicAgency } from "@/lib/client-portal-api";

export default function AgencyPublicSpaceScreen() {
  const { slug } = useLocalSearchParams<{ slug: string }>();
  const [agency, setAgency] = useState<PublicAgency | null>(null);
  const [error, setError] = useState("");

  useEffect(() => {
    if (!slug) return;
    void fetchPublicAgency(slug).then(setAgency).catch((caughtError) => setError(caughtError instanceof Error ? caughtError.message : "Espace indisponible."));
  }, [slug]);

  if (!agency && !error) return <ScreenContainer><View style={styles.center}><ActivityIndicator color="#007FFF" /><Text style={styles.loading}>Chargement de l’espace agence…</Text></View></ScreenContainer>;
  if (!agency) return <ScreenContainer><View style={styles.center}><MaterialIcons name="domain-disabled" size={36} color="#CE1126" /><Text style={styles.errorTitle}>Espace indisponible</Text><Text style={styles.errorCopy}>{error}</Text><Pressable onPress={() => router.replace("/login" as never)} style={styles.backButton}><Text style={styles.backText}>Retour à GlobalLogix</Text></Pressable></View></ScreenContainer>;

  const primary = /^#[0-9A-F]{6}$/i.test(agency.primaryColor ?? "") ? agency.primaryColor! : "#007FFF";
  return <ScreenContainer><View style={styles.page}><View style={[styles.hero, { backgroundColor: primary }]}><View style={styles.topline}><Text style={styles.network}>PROPULSÉ PAR GLOBALLOGIX</Text><Pressable onPress={() => router.push("/login" as never)} style={styles.adminLink}><Text style={styles.adminLinkText}>Administration</Text></Pressable></View><View style={styles.brandRow}><View style={styles.logo}>{agency.logoUrl ? <Image source={{ uri: agency.logoUrl }} style={styles.logoImage} /> : <MaterialIcons name="local-shipping" size={34} color={primary} />}</View><View style={styles.brandCopy}><Text style={styles.agencyName}>{agency.displayName}</Text><Text style={styles.agencySub}>Suivi d’expéditions et relation client</Text></View></View></View><View style={styles.content}><Text style={styles.eyebrow}>ESPACE CLIENT SÉCURISÉ</Text><Text style={styles.title}>Suivez tous vos colis</Text><Text style={styles.copy}>Créez un seul compte avec votre numéro WhatsApp. Après vérification par SMS, vous accédez uniquement aux colis que {agency.displayName} a rattachés à votre numéro.</Text><Pressable onPress={() => router.push({ pathname: "/client", params: { agency: agency.publicSlug } } as never)} style={({ pressed }) => [styles.clientButton, { backgroundColor: primary }, pressed && styles.pressed]}><MaterialIcons name="phone-android" size={19} color="#FFFFFF" /><Text style={styles.clientButtonText}>Ouvrir mon espace client</Text></Pressable><View style={styles.security}><MaterialIcons name="verified-user" size={18} color={primary} /><Text style={styles.securityText}>Un numéro WhatsApp est associé à un seul compte client. Les données d’autres agences ne sont jamais visibles depuis cet espace.</Text></View><View style={styles.contact}><Text style={styles.contactTitle}>CONTACT DE L’AGENCE</Text>{agency.publicEmail ? <Text style={styles.contactValue}>{agency.publicEmail}</Text> : null}{agency.publicPhone ? <Text style={styles.contactValue}>{agency.publicPhone}</Text> : null}{agency.supportHours ? <Text style={styles.contactMeta}>{agency.supportHours}</Text> : null}{!agency.publicEmail && !agency.publicPhone ? <Text style={styles.contactMeta}>Les coordonnées de l’agence seront publiées prochainement.</Text> : null}</View></View></View></ScreenContainer>;
}

const styles = StyleSheet.create({
  page: { backgroundColor: "#F5F9FD", flex: 1 }, center: { alignItems: "center", flex: 1, justifyContent: "center", padding: 26 }, loading: { color: "#65768B", fontSize: 13, marginTop: 10 }, errorTitle: { color: "#062B5C", fontSize: 21, fontWeight: "900", marginTop: 11 }, errorCopy: { color: "#65768B", fontSize: 13, lineHeight: 19, marginTop: 7, textAlign: "center" }, backButton: { backgroundColor: "#003F87", borderRadius: 10, marginTop: 16, paddingHorizontal: 15, paddingVertical: 11 }, backText: { color: "#FFFFFF", fontSize: 12, fontWeight: "900" }, hero: { padding: 20, paddingTop: 28 }, topline: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, network: { color: "#EAF5FF", fontSize: 9, fontWeight: "900", letterSpacing: 0.9 }, adminLink: { borderColor: "#FFFFFF77", borderRadius: 9, borderWidth: 1, paddingHorizontal: 9, paddingVertical: 6 }, adminLinkText: { color: "#FFFFFF", fontSize: 10, fontWeight: "900" }, brandRow: { alignItems: "center", flexDirection: "row", marginTop: 26 }, logo: { alignItems: "center", backgroundColor: "#FFFFFF", borderRadius: 17, height: 68, justifyContent: "center", overflow: "hidden", width: 68 }, logoImage: { height: 60, resizeMode: "contain", width: 60 }, brandCopy: { flex: 1, marginLeft: 13 }, agencyName: { color: "#FFFFFF", fontSize: 25, fontWeight: "900" }, agencySub: { color: "#EAF5FF", fontSize: 12, lineHeight: 17, marginTop: 4 }, content: { flex: 1, padding: 21 }, eyebrow: { color: "#CE1126", fontSize: 10, fontWeight: "900", letterSpacing: 1, marginTop: 8 }, title: { color: "#062B5C", fontSize: 25, fontWeight: "900", marginTop: 5 }, copy: { color: "#5B6D84", fontSize: 13, lineHeight: 20, marginTop: 8 }, clientButton: { alignItems: "center", borderRadius: 13, flexDirection: "row", gap: 8, justifyContent: "center", marginTop: 20, minHeight: 53 }, clientButtonText: { color: "#FFFFFF", fontSize: 13, fontWeight: "900" }, security: { alignItems: "flex-start", backgroundColor: "#EAF4FD", borderRadius: 13, flexDirection: "row", gap: 8, marginTop: 16, padding: 12 }, securityText: { color: "#415F80", flex: 1, fontSize: 10, lineHeight: 15 }, contact: { backgroundColor: "#FFFFFF", borderColor: "#D9E2EC", borderRadius: 14, borderWidth: 1, marginTop: 16, padding: 13 }, contactTitle: { color: "#415F80", fontSize: 10, fontWeight: "900", letterSpacing: 0.8 }, contactValue: { color: "#062B5C", fontSize: 12, fontWeight: "800", marginTop: 6 }, contactMeta: { color: "#65768B", fontSize: 11, marginTop: 6 }, pressed: { opacity: 0.82, transform: [{ scale: 0.99 }] },
});
