import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { fetchAgencyClientDetail, type AgencyClientShipment } from "@/lib/agency-api";

const modeStatus: Record<string, { label: string; color: string }> = { delivered: { label: "Livré", color: "#147A46" }, delayed: { label: "Retard", color: "#B4232B" }, customs: { label: "Douane", color: "#936200" }, in_transit: { label: "En transit", color: "#003F87" }, planned: { label: "Planifié", color: "#415F80" }, cancelled: { label: "Annulé", color: "#65768B" } };

export default function AgencyClientDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const [detail, setDetail] = useState<Awaited<ReturnType<typeof fetchAgencyClientDetail>> | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { if (!id) return; void fetchAgencyClientDetail(id).then(setDetail).catch((caughtError) => setError(caughtError instanceof Error ? caughtError.message : "Chargement impossible.")); }, [id]);
  const stats = useMemo(() => ({ active: detail?.shipments.filter((shipment) => shipment.status !== "delivered" && shipment.status !== "cancelled").length ?? 0, risk: detail?.shipments.filter((shipment) => shipment.status === "delayed").length ?? 0 }), [detail]);
  if (!detail && !error) return <ScreenContainer><View style={styles.center}><ActivityIndicator color="#007FFF" /><Text style={styles.loading}>Chargement du dossier client…</Text></View></ScreenContainer>;
  if (!detail) return <ScreenContainer><View style={styles.center}><MaterialIcons name="person-off" size={35} color="#CE1126" /><Text style={styles.errorTitle}>Dossier client indisponible</Text><Text style={styles.errorCopy}>{error}</Text><Pressable onPress={() => router.back()} style={styles.backButton}><Text style={styles.backButtonText}>Retour aux clients</Text></Pressable></View></ScreenContainer>;
  return <ScreenContainer><FlatList data={detail.shipments} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<View><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={20} color="#062B5C" /><Text style={styles.backText}>Mes clients</Text></Pressable><View style={styles.profile}><View style={styles.avatar}><Text style={styles.avatarText}>{(detail.client.displayName ?? "C").slice(0, 1).toUpperCase()}</Text></View><View style={styles.profileCopy}><Text style={styles.eyebrow}>DOSSIER CLIENT</Text><Text style={styles.name}>{detail.client.displayName || "Client sans nom affiché"}</Text><Text style={styles.phone}>WhatsApp · ••••{detail.client.phoneLast4 ?? "—"}</Text></View></View><View style={styles.metrics}><Text style={styles.metric}><Text style={styles.metricValue}>{detail.shipments.length}</Text> colis</Text><Text style={styles.metric}><Text style={styles.metricValue}>{stats.active}</Text> actifs</Text><Text style={[styles.metric, stats.risk > 0 && styles.risk]}><Text style={styles.metricValue}>{stats.risk}</Text> à risque</Text></View><Text style={styles.section}>COLIS ASSOCIÉS À CE NUMÉRO</Text></View>} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyText}>Aucun colis n’est actuellement associé à ce client dans votre agence.</Text></View>} renderItem={({ item }) => <ShipmentRow shipment={item} />} /></ScreenContainer>;
}

function ShipmentRow({ shipment }: { shipment: AgencyClientShipment }) { const status = modeStatus[shipment.status] ?? { label: shipment.status, color: "#415F80" }; return <View style={styles.shipment}><View style={[styles.statusIcon, { backgroundColor: `${status.color}18` }]}><MaterialIcons name="local-shipping" size={20} color={status.color} /></View><View style={styles.shipmentCopy}><View style={styles.shipmentTop}><Text style={styles.tracking}>{shipment.trackingNumber}</Text><Text style={[styles.status, { color: status.color }]}>{status.label}</Text></View><Text numberOfLines={1} style={styles.route}>{shipment.origin} → {shipment.destination}</Text><Text style={styles.position}>{shipment.currentPosition ?? "Position en attente"}</Text><View style={styles.track}><View style={[styles.fill, { width: `${Math.max(0, Math.min(100, shipment.progress))}%`, backgroundColor: status.color }]} /></View></View></View>; }

const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 32 }, center: { alignItems: "center", flex: 1, justifyContent: "center", padding: 26 }, loading: { color: "#65768B", fontSize: 13, marginTop: 10 }, errorTitle: { color: "#062B5C", fontSize: 20, fontWeight: "900", marginTop: 10 }, errorCopy: { color: "#65768B", fontSize: 13, lineHeight: 19, marginTop: 6, textAlign: "center" }, backButton: { backgroundColor: "#003F87", borderRadius: 10, marginTop: 15, paddingHorizontal: 14, paddingVertical: 10 }, backButtonText: { color: "#FFFFFF", fontSize: 12, fontWeight: "900" }, back: { alignItems: "center", flexDirection: "row", gap: 6, height: 40 }, backText: { color: "#062B5C", fontWeight: "800" }, profile: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#D9E2EC", borderRadius: 16, borderWidth: 1, flexDirection: "row", marginTop: 14, padding: 14 }, avatar: { alignItems: "center", backgroundColor: "#EAF4FD", borderRadius: 24, height: 48, justifyContent: "center", width: 48 }, avatarText: { color: "#003F87", fontSize: 19, fontWeight: "900" }, profileCopy: { flex: 1, marginLeft: 11 }, eyebrow: { color: "#CE1126", fontSize: 9, fontWeight: "900", letterSpacing: 0.8 }, name: { color: "#062B5C", fontSize: 17, fontWeight: "900", marginTop: 3 }, phone: { color: "#415F80", fontSize: 11, fontWeight: "800", marginTop: 4 }, metrics: { flexDirection: "row", gap: 8, marginTop: 12 }, metric: { backgroundColor: "#F3F8FC", borderRadius: 10, color: "#415F80", flex: 1, fontSize: 10, padding: 10, textAlign: "center" }, metricValue: { color: "#062B5C", fontSize: 17, fontWeight: "900" }, risk: { color: "#B4232B" }, section: { color: "#718496", fontSize: 10, fontWeight: "900", letterSpacing: 0.8, marginBottom: 9, marginTop: 20 }, shipment: { alignItems: "flex-start", backgroundColor: "#FFFFFF", borderColor: "#D9E2EC", borderRadius: 15, borderWidth: 1, flexDirection: "row", marginBottom: 9, padding: 12 }, statusIcon: { alignItems: "center", borderRadius: 12, height: 40, justifyContent: "center", marginRight: 10, width: 40 }, shipmentCopy: { flex: 1 }, shipmentTop: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, tracking: { color: "#062B5C", fontSize: 13, fontWeight: "900" }, status: { fontSize: 10, fontWeight: "900" }, route: { color: "#65768B", fontSize: 10, marginTop: 4 }, position: { color: "#415F80", fontSize: 10, marginTop: 4 }, track: { backgroundColor: "#E8EFF5", borderRadius: 99, height: 5, marginTop: 8, overflow: "hidden" }, fill: { borderRadius: 99, height: 5 }, empty: { backgroundColor: "#FFFFFF", borderColor: "#D9E2EC", borderRadius: 14, borderWidth: 1, padding: 20 }, emptyText: { color: "#65768B", fontSize: 12, lineHeight: 18, textAlign: "center" }, });
