import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { useAuth } from "@/lib/auth-context";
import { fetchAgencyClients, type AgencyClientSummary } from "@/lib/agency-api";

export default function AgencyClientsScreen() {
  const { user } = useAuth();
  const canManage = user?.role === "agency_admin" && Boolean(user.agencyId);
  const [clients, setClients] = useState<AgencyClientSummary[]>([]);
  const [query, setQuery] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const load = useCallback(async () => {
    if (!canManage) { setLoading(false); return; }
    try { setLoading(true); setError(""); const result = await fetchAgencyClients(); setClients(result.clients); }
    catch (caughtError) { setError(caughtError instanceof Error ? caughtError.message : "Chargement des clients impossible."); }
    finally { setLoading(false); }
  }, [canManage]);
  useEffect(() => { void load(); }, [load]);

  const visible = useMemo(() => {
    const normalized = query.trim().toLocaleLowerCase("fr-FR");
    if (!normalized) return clients;
    return clients.filter((client) => [client.displayName ?? "", client.phoneLast4 ?? "", String(client.shipmentCount)].some((value) => value.toLocaleLowerCase("fr-FR").includes(normalized)));
  }, [clients, query]);
  const stats = useMemo(() => clients.reduce((total, client) => ({ active: total.active + client.activeShipments, risk: total.risk + client.atRiskShipments }), { active: 0, risk: 0 }), [clients]);

  if (!canManage) return <ScreenContainer><View style={styles.denied}><MaterialIcons name="lock" size={34} color="#CE1126" /><Text style={styles.deniedTitle}>Accès agence requis</Text><Text style={styles.deniedText}>Seul l’administrateur de l’agence peut consulter ses clients et leurs colis associés.</Text></View></ScreenContainer>;
  if (loading) return <ScreenContainer><View style={styles.loader}><ActivityIndicator color="#007FFF" /><Text style={styles.loaderText}>Chargement des clients…</Text></View></ScreenContainer>;

  return <ScreenContainer><FlatList data={visible} keyExtractor={(item) => item.firebaseUid} contentContainerStyle={styles.content} refreshing={loading} onRefresh={() => void load()} ListHeaderComponent={<View><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={20} color="#062B5C" /><Text style={styles.backText}>Réglages</Text></Pressable><Text style={styles.eyebrow}>RELATION CLIENT · AGENCE</Text><Text style={styles.title}>Mes clients</Text><Text style={styles.subtitle}>Chaque ligne représente un compte vérifié par SMS. Les numéros WhatsApp sont masqués et seuls les colis de votre agence sont visibles.</Text><View style={styles.metrics}><Metric icon="groups" label="Clients" value={clients.length} color="#007FFF" /><Metric icon="local-shipping" label="Actifs" value={stats.active} color="#0F766E" /><Metric icon="priority-high" label="À risque" value={stats.risk} color="#CE1126" /></View><View style={styles.search}><MaterialIcons name="search" size={19} color="#718496" /><TextInput value={query} onChangeText={setQuery} placeholder="Rechercher un client ou ••••1234" placeholderTextColor="#718496" style={styles.searchInput} autoCapitalize="none" autoCorrect={false} /><Text style={styles.count}>{visible.length}/{clients.length}</Text></View>{error ? <Text style={styles.error}>{error}</Text> : null}<Text style={styles.section}>COMPTES CLIENTS DE VOTRE AGENCE</Text></View>} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="group-off" size={32} color="#718496" /><Text style={styles.emptyTitle}>{query ? "Aucun résultat" : "Aucun client associé"}</Text><Text style={styles.emptyCopy}>{query ? "Essayez le nom ou les quatre derniers chiffres du numéro WhatsApp." : "Les clients apparaîtront lorsqu’un numéro WhatsApp vérifié sera rattaché à un colis de votre agence."}</Text></View>} renderItem={({ item }) => <Pressable onPress={() => router.push({ pathname: "/agency-client/[id]", params: { id: item.firebaseUid } } as never)} style={({ pressed }) => [styles.clientCard, pressed && styles.pressed]}><View style={styles.avatar}><Text style={styles.avatarText}>{(item.displayName ?? "C").slice(0, 1).toUpperCase()}</Text></View><View style={styles.clientCopy}><View style={styles.clientTop}><Text numberOfLines={1} style={styles.clientName}>{item.displayName || "Client sans nom affiché"}</Text>{item.atRiskShipments > 0 ? <View style={styles.riskBadge}><Text style={styles.riskBadgeText}>{item.atRiskShipments} RISQUE</Text></View> : null}</View><Text style={styles.phone}>WhatsApp · ••••{item.phoneLast4 ?? "—"}</Text><Text style={styles.clientMeta}>{item.shipmentCount} colis · {item.activeShipments} actif{item.activeShipments > 1 ? "s" : ""} · {item.deliveredShipments} livré{item.deliveredShipments > 1 ? "s" : ""}</Text></View><MaterialIcons name="chevron-right" size={22} color="#718496" /></Pressable>} /></ScreenContainer>;
}

function Metric({ icon, label, value, color }: { icon: "groups" | "local-shipping" | "priority-high"; label: string; value: number; color: string }) { return <View style={styles.metric}><MaterialIcons name={icon} size={18} color={color} /><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }

const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 34 }, back: { alignItems: "center", flexDirection: "row", gap: 6, height: 40 }, backText: { color: "#062B5C", fontWeight: "800" }, eyebrow: { color: "#CE1126", fontSize: 10, fontWeight: "900", letterSpacing: 1.1, marginTop: 13 }, title: { color: "#062B5C", fontSize: 27, fontWeight: "900", marginTop: 5 }, subtitle: { color: "#65768B", fontSize: 13, lineHeight: 19, marginTop: 8 }, metrics: { flexDirection: "row", gap: 9, marginTop: 17 }, metric: { backgroundColor: "#FFFFFF", borderColor: "#D9E2EC", borderRadius: 14, borderWidth: 1, flex: 1, padding: 11 }, metricValue: { color: "#062B5C", fontSize: 21, fontWeight: "900", marginTop: 6 }, metricLabel: { color: "#65768B", fontSize: 10, fontWeight: "800", marginTop: 2 }, search: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#D9E2EC", borderRadius: 12, borderWidth: 1, flexDirection: "row", height: 48, marginTop: 14, paddingHorizontal: 12 }, searchInput: { color: "#062B5C", flex: 1, fontSize: 13, height: 46, marginLeft: 8 }, count: { color: "#718496", fontSize: 11, fontWeight: "900" }, section: { color: "#718496", fontSize: 10, fontWeight: "900", letterSpacing: 0.8, marginBottom: 9, marginTop: 20 }, error: { color: "#B4232B", fontSize: 11, lineHeight: 16, marginTop: 10 }, clientCard: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#D9E2EC", borderRadius: 15, borderWidth: 1, flexDirection: "row", marginBottom: 9, padding: 12 }, avatar: { alignItems: "center", backgroundColor: "#EAF4FD", borderRadius: 18, height: 38, justifyContent: "center", marginRight: 10, width: 38 }, avatarText: { color: "#003F87", fontSize: 14, fontWeight: "900" }, clientCopy: { flex: 1 }, clientTop: { alignItems: "center", flexDirection: "row", gap: 7 }, clientName: { color: "#062B5C", flex: 1, fontSize: 13, fontWeight: "900" }, riskBadge: { backgroundColor: "#FDEBEC", borderRadius: 99, paddingHorizontal: 6, paddingVertical: 3 }, riskBadgeText: { color: "#B4232B", fontSize: 8, fontWeight: "900" }, phone: { color: "#415F80", fontSize: 10, fontWeight: "800", marginTop: 4 }, clientMeta: { color: "#65768B", fontSize: 10, marginTop: 4 }, empty: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#D9E2EC", borderRadius: 15, borderWidth: 1, padding: 25 }, emptyTitle: { color: "#062B5C", fontSize: 15, fontWeight: "900", marginTop: 9 }, emptyCopy: { color: "#65768B", fontSize: 11, lineHeight: 16, marginTop: 5, textAlign: "center" }, denied: { alignItems: "center", flex: 1, justifyContent: "center", padding: 26 }, deniedTitle: { color: "#062B5C", fontSize: 21, fontWeight: "900", marginTop: 12 }, deniedText: { color: "#65768B", fontSize: 13, lineHeight: 19, marginTop: 6, textAlign: "center" }, loader: { alignItems: "center", flex: 1, justifyContent: "center" }, loaderText: { color: "#65768B", fontSize: 13, marginTop: 10 }, pressed: { opacity: 0.78, transform: [{ scale: 0.99 }] }, });
