import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { fetchAgencyProfile } from "@/lib/agency-api";
import { firebaseSmsTestInstructions, validateFirebaseSmsTestSetup } from "@/lib/firebase-sms-test-policy";
import { useAuth } from "@/lib/auth-context";

export default function FirebaseSmsTestScreen() {
  const { user } = useAuth();
  const canManage = user?.role === "agency_admin" && Boolean(user.agencyId);
  const [publicPath, setPublicPath] = useState("/agency/votre-agence");
  const [testPhone, setTestPhone] = useState("");
  const [testCode, setTestCode] = useState("");
  const [result, setResult] = useState("");
  const [loading, setLoading] = useState(true);
  useEffect(() => { if (!canManage) { setLoading(false); return; } void fetchAgencyProfile().then(({ profile }) => { if (profile?.publicSlug) setPublicPath(`/agency/${profile.publicSlug}`); }).finally(() => setLoading(false)); }, [canManage]);
  const instructions = firebaseSmsTestInstructions(publicPath);
  const validate = () => { try { const validated = validateFirebaseSmsTestSetup(testPhone, testCode); setResult(`Format validé pour ••••${validated.normalizedPhone.slice(-4)}. Ces valeurs restent sur cet écran et ne sont pas enregistrées.`); } catch (error) { setResult(error instanceof Error ? error.message : "Configuration de test invalide."); } };
  if (!canManage) return <ScreenContainer><View style={styles.center}><MaterialIcons name="lock" size={34} color="#CE1126" /><Text style={styles.denied}>Accès administrateur d’agence requis</Text></View></ScreenContainer>;
  if (loading) return <ScreenContainer><View style={styles.center}><ActivityIndicator color="#007FFF" /></View></ScreenContainer>;
  return <ScreenContainer><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={20} color="#062B5C" /><Text style={styles.backText}>Identité et messages client</Text></Pressable><Text style={styles.eyebrow}>FIREBASE · TEST SMS</Text><Text style={styles.title}>Préparer un numéro de test</Text><Text style={styles.subtitle}>Cette page facilite l’essai du portail client. Le numéro et son code doivent d’abord être configurés dans Firebase Authentication ; ils ne sont pas conservés dans GlobalLogix.</Text><View style={styles.warning}><MaterialIcons name="admin-panel-settings" size={20} color="#003F87" /><Text style={styles.warningText}>Pour des raisons de sécurité, l’application ne peut ni créer ni lire les numéros de test Firebase. Configurez-les uniquement dans la console Firebase, puis utilisez cet écran pour vérifier le format et ouvrir le parcours client.</Text></View><Text style={styles.section}>ÉTAPES DE CONFIGURATION</Text>{instructions.steps.map((step, index) => <View key={step} style={styles.step}><Text style={styles.stepIndex}>{index + 1}</Text><Text style={styles.stepText}>{step}</Text></View>)}<Text style={styles.section}>VÉRIFICATION LOCALE DU SCÉNARIO</Text><Text style={styles.label}>Numéro WhatsApp de test (international)</Text><TextInput value={testPhone} onChangeText={setTestPhone} placeholder="+243 812 345 678" keyboardType="phone-pad" autoComplete="tel" style={styles.input} /><Text style={styles.label}>Code Firebase de test (6 chiffres)</Text><TextInput value={testCode} onChangeText={setTestCode} placeholder="123456" keyboardType="number-pad" maxLength={6} style={styles.input} /><Pressable onPress={validate} style={({ pressed }) => [styles.validateButton, pressed && styles.pressed]}><MaterialIcons name="verified-user" size={18} color="#062B5C" /><Text style={styles.validateText}>Vérifier le scénario</Text></Pressable>{result ? <Text style={[styles.result, result.startsWith("Format") ? styles.success : styles.error]}>{result}</Text> : null}<Pressable onPress={() => router.push({ pathname: "/client", params: { agency: publicPath.split("/").pop() } } as never)} style={({ pressed }) => [styles.openButton, pressed && styles.pressed]}><MaterialIcons name="open-in-new" size={18} color="#FFFFFF" /><Text style={styles.openText}>Ouvrir le portail client de test</Text></Pressable><Text style={styles.privacy}>{instructions.privacy}</Text></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 36 }, center: { alignItems: "center", flex: 1, justifyContent: "center", padding: 26 }, denied: { color: "#062B5C", fontSize: 17, fontWeight: "900", marginTop: 10, textAlign: "center" }, back: { alignItems: "center", flexDirection: "row", gap: 6, height: 40 }, backText: { color: "#062B5C", fontWeight: "800" }, eyebrow: { color: "#CE1126", fontSize: 10, fontWeight: "900", letterSpacing: 1, marginTop: 12 }, title: { color: "#062B5C", fontSize: 25, fontWeight: "900", marginTop: 5 }, subtitle: { color: "#65768B", fontSize: 13, lineHeight: 19, marginTop: 8 }, warning: { alignItems: "flex-start", backgroundColor: "#EAF4FD", borderRadius: 13, flexDirection: "row", gap: 9, marginTop: 16, padding: 12 }, warningText: { color: "#274C73", flex: 1, fontSize: 11, lineHeight: 17 }, section: { color: "#CE1126", fontSize: 10, fontWeight: "900", letterSpacing: 0.9, marginBottom: 10, marginTop: 22 }, step: { alignItems: "flex-start", backgroundColor: "#FFFFFF", borderColor: "#D9E2EC", borderRadius: 12, borderWidth: 1, flexDirection: "row", gap: 10, marginBottom: 8, padding: 11 }, stepIndex: { alignItems: "center", backgroundColor: "#003F87", borderRadius: 11, color: "#FFFFFF", fontSize: 11, fontWeight: "900", height: 22, lineHeight: 22, textAlign: "center", width: 22 }, stepText: { color: "#415F80", flex: 1, fontSize: 11, lineHeight: 16 }, label: { color: "#062B5C", fontSize: 12, fontWeight: "800", marginBottom: 6, marginTop: 12 }, input: { backgroundColor: "#FFFFFF", borderColor: "#C8DFF5", borderRadius: 12, borderWidth: 1, color: "#062B5C", fontSize: 14, height: 48, paddingHorizontal: 12 }, validateButton: { alignItems: "center", backgroundColor: "#F7D116", borderRadius: 12, flexDirection: "row", gap: 7, height: 50, justifyContent: "center", marginTop: 15 }, validateText: { color: "#062B5C", fontSize: 13, fontWeight: "900" }, result: { fontSize: 11, lineHeight: 16, marginTop: 10, textAlign: "center" }, success: { color: "#147A46" }, error: { color: "#B4232B" }, openButton: { alignItems: "center", backgroundColor: "#003F87", borderRadius: 12, flexDirection: "row", gap: 7, height: 50, justifyContent: "center", marginTop: 17 }, openText: { color: "#FFFFFF", fontSize: 13, fontWeight: "900" }, privacy: { color: "#718496", fontSize: 10, lineHeight: 15, marginTop: 12, textAlign: "center" }, pressed: { opacity: 0.8, transform: [{ scale: 0.985 }] } });
