import type { Shipment } from "./types";

export const DEMO_SHIPMENTS: Shipment[] = [
  {
    id: "GLX-801",
    trackingNumber: "GLX-801-DXB-KIN",
    origin: "Dubaï, EAU",
    destination: "Kinshasa, RDC",
    mode: "air",
    status: "in-transit",
    progress: 64,
    distanceRemainingKm: 2840,
    eta: "Aujourd’hui · 19:40",
    lastTelemetryAt: "Signal en attente",
    currentPosition: "Couloir aérien Afrique de l’Est",
  },
  {
    id: "GLX-806",
    trackingNumber: "GLX-806-MAT-PAR",
    origin: "Matadi, RDC",
    destination: "Paris, France",
    mode: "sea",
    status: "customs",
    progress: 41,
    distanceRemainingKm: 6070,
    eta: "28 août · 08:15",
    lastTelemetryAt: "Signal en attente",
    currentPosition: "Port de Matadi",
  },
  {
    id: "GLX-824",
    trackingNumber: "GLX-824-KIN-LUB",
    origin: "Kinshasa, RDC",
    destination: "Lubumbashi, RDC",
    mode: "land",
    status: "delayed",
    progress: 78,
    distanceRemainingKm: 315,
    eta: "Demain · 10:30",
    lastTelemetryAt: "Signal en attente",
    currentPosition: "Kasai central",
  },
  {
    id: "GLX-831",
    trackingNumber: "GLX-831-CDG-FIH",
    origin: "Paris, France",
    destination: "Kinshasa, RDC",
    mode: "air",
    status: "in-transit",
    progress: 29,
    distanceRemainingKm: 5110,
    eta: "29 août · 14:10",
    lastTelemetryAt: "Signal en attente",
    currentPosition: "Hub cargo CDG",
  },
];
